# Generated by Django 3.1.1 on 2020-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pacakges',
            field=models.CharField(choices=[('FULL DAY SPA', 'Full Day Spa'), ('HALF DAY SPA', 'Half Day Spa'), ('MOONLIGHT SPA', 'Moonlight Spa')], default='FULL DAY SPA', max_length=100),
        ),
    ]
