# Generated by Django 3.1.1 on 2020-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
