# Generated by Django 3.1.1 on 2020-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20201127_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
    ]
