# Generated by Django 3.1.1 on 2020-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
