# Generated by Django 3.1.1 on 2020-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
