# Generated by Django 3.1.1 on 2020-12-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_auto_20201201_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
