# Generated by Django 3.1.1 on 2020-12-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201205_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedroom',
            name='room_category',
        ),
        migrations.AddField(
            model_name='reservedroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('SIN', 'Single'), ('DUO', 'Double'), ('TRIP', 'Triple'), ('KIN', 'king'), ('QUE', 'Queen'), ('SUI', 'Suite')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
    ]
