# Generated by Django 3.1.1 on 2020-12-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, null=True)),
                ('max_capacity', models.IntegerField(null=True)),
                ('room_category', models.CharField(choices=[('SIN', 'Single'), ('DUO', 'Double'), ('TRIP', 'Triple'), ('KIN', 'king'), ('QUE', 'Queen'), ('SUI', 'Suite')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservedroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='reservedroom',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomcategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomcategory'),
        ),
    ]
