# Generated by Django 3.1.1 on 2020-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20201205_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='beds',
            field=models.IntegerField(null=True),
        ),
    ]
