# Generated by Django 3.1.1 on 2020-12-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
    ]
