# Generated by Django 3.1.1 on 2020-12-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_room_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_out',
            new_name='check_out',
        ),
    ]
