# Generated by Django 3.1.4 on 2020-12-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_auto_20201208_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_out',
        ),
    ]
